name: 'Check Playwright Version'
description: 'Verify Playwright version sync between package.json and Docker container'
runs:
  using: "composite"
  steps:
    - name: Verify Playwright version sync
      shell: bash
      run: |
        # Get Playwright version from package.json
        PACKAGE_VERSION=$(node -p "require('./package.json').devDependencies['@playwright/test']" | sed 's/[\^~]//')
        # Get container version from environment (set by Docker image)
        CONTAINER_VERSION=$(npx playwright --version | awk '{print $2}')
        
        echo "📦 package.json @playwright/test: $PACKAGE_VERSION"
        echo "🐳 Docker container Playwright:   $CONTAINER_VERSION"
        
        if [ "$PACKAGE_VERSION" != "$CONTAINER_VERSION" ]; then
          echo ""
          echo "❌ VERSION MISMATCH!"
          echo "Please update the Docker image in this workflow to:"
          echo "  image: mcr.microsoft.com/playwright:v${PACKAGE_VERSION}-noble"
          exit 1
        fi
        echo "✅ Versions match!"
