name: 'Merge Cucumber Results'
description: 'Merge cucumber reports and upload artifacts'
inputs:
  start-time:
    description: 'Start time of the workflow'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: cucumber-report-*
        merge-multiple: true
        path: all-cucumber-reports

    - name: Merge reports
      shell: bash
      env:
        START_TIME: ${{ inputs.start-time }}
      run: node scripts/reporting/merge-cucumber-reports.js

    - name: Capture Report Screenshot
      shell: bash
      run: node scripts/reporting/capture-report-screenshot.js

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-html-report
        path: cucumber-report
        retention-days: 30

    - name: Upload report summary
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report-summary
        path: cucumber-report/cucumber-report-summary.png
        retention-days: 30
